describe("the-internet", () => {
  beforeEach(() => {
    cy.visit("https://the-internet.herokuapp.com/")
  })

  it('the h1 contains the correct text', () => {
    cy.get('h1').contains('Welcome to the-internet')
  })

  it("the features on the homepage are correct", () => {
    cy.get("li").eq(0).contains("A/B Testing")
    cy.get("li").eq(1).contains("Add/Remove Elements")
    cy.get("li").eq(2).contains("Basic Auth")
    cy.get("li").eq(3).contains("Broken Images")
    cy.get("li").eq(4).contains("Challenging DOM")
    cy.get("li").eq(5).contains("Checkboxes")
    cy.get("li").eq(6).contains("Context Menu")
    cy.get("li").eq(7).contains("Digest Authentication")
    cy.get("li").eq(8).contains("Disappearing Elements")
    cy.get("li").eq(9).contains("Drag and Drop")
    cy.get("li").eq(10).contains("Dropdown")
    cy.get("li").eq(11).contains("Dynamic Content")
    cy.get("li").eq(12).contains("Dynamic Controls")
    cy.get("li").eq(13).contains("Dynamic Loading")
    cy.get("li").eq(14).contains("Entry Ad")
    cy.get("li").eq(15).contains("Exit Intent")
    cy.get("li").eq(16).contains("File Download")
    cy.get("li").eq(17).contains("File Upload")
    cy.get("li").eq(18).contains("Floating Menu")
    cy.get("li").eq(19).contains("Forgot Password")
    cy.get("li").eq(20).contains("Form Authentication")
    cy.get("li").eq(21).contains("Frames")
    cy.get("li").eq(22).contains("Geolocation")
    cy.get("li").eq(23).contains("Horizontal Slider")
    cy.get("li").eq(24).contains("Hovers")
    cy.get("li").eq(25).contains("Infinite Scroll")
    cy.get("li").eq(26).contains("Inputs")
    cy.get("li").eq(27).contains("JQuery UI Menus")
    cy.get("li").eq(28).contains("JavaScript Alerts")
    cy.get("li").eq(29).contains("JavaScript onload event error")
    cy.get("li").eq(30).contains("Key Presses")
    cy.get("li").eq(31).contains("Large & Deep DOM")
    cy.get("li").eq(32).contains("Multiple Windows")
    cy.get("li").eq(33).contains("Nested Frames")
    cy.get("li").eq(34).contains("Notification Messages")
    cy.get("li").eq(35).contains("Redirect Link")
    cy.get("li").eq(36).contains("Secure File Download")
    cy.get("li").eq(37).contains("Shadow DOM")
    cy.get("li").eq(38).contains("Shifting Content")
    cy.get("li").eq(39).contains("Slow Resources")
    cy.get("li").eq(40).contains("Sortable Data Tables")
    cy.get("li").eq(41).contains("Status Codes")
    cy.get("li").eq(42).contains("Typos")
    cy.get("li").eq(43).contains("WYSIWYG Editor")
  })
})
